[package]
name = "trail_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leaflet = "^0.2.1"
seed = "^0.8.0"
web-sys = { version = "^0.3.55", features = ["console"] }
